authMethod: http
authHTTPAddress: https://nyone.app/internal/mediamtx/auth?secret=change-this-secret
authHTTPExclude:
  - action: read
  - action: playback
  - action: api
  - action: metrics
  - action: pprof

api: yes
apiAddress: 127.0.0.1:9997

rtmp: yes
rtmpAddress: :19935

hls: yes
hlsAddress: :19988
hlsVariant: mpegts
hlsAllowOrigins:
  - https://nyone.app


pathDefaults:
  record: yes
  recordPath: ./storage/app/private/recordings/%path/%Y-%m-%d_%H-%M-%S-%f

  runOnReady: curl -X POST "https://nyone.app/internal/mediamtx/ready?secret=change-this-secret" --data-urlencode "path=$MTX_PATH" --data-urlencode "source_type=$MTX_SOURCE_TYPE" --data-urlencode "source_id=$MTX_SOURCE_ID"
  runOnReadyRestart: no
  runOnNotReady: curl -X POST "https://nyone.app/internal/mediamtx/not-ready?secret=change-this-secret" --data-urlencode "path=$MTX_PATH" --data-urlencode "source_type=$MTX_SOURCE_TYPE" --data-urlencode "source_id=$MTX_SOURCE_ID"
  runOnRecordSegmentComplete: curl -X POST "https://nyone.app/internal/mediamtx/recording-complete?secret=change-this-secret" --data-urlencode "path=$MTX_PATH" --data-urlencode "segment_path=$MTX_SEGMENT_PATH" --data-urlencode "duration=$MTX_SEGMENT_DURATION"

paths:
  all_others:
    source: publisher
